# Generated by Django 5.2.5 on 2025-08-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('dus', models.CharField(max_length=100)),
                ('catalog_link', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MajorVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_kind', models.CharField(max_length=100)),
                ('concentration1', models.CharField(max_length=100)),
                ('concentration2', models.CharField(max_length=100)),
                ('concentration3', models.CharField(max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.major')),
            ],
        ),
        migrations.CreateModel(
            name='MajorVersionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('SINGLE', 'Single'), ('CATEGORY', 'Category'), ('ELECTIVE', 'Elective'), ('SENIOR', 'Senior')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('credits', models.PositiveIntegerField()),
                ('major_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.majorversion')),
            ],
        ),
        migrations.CreateModel(
            name='MajorVersionRequirementsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('major_version_reqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.majorversionrequirements')),
            ],
        ),
    ]
