# Generated by Django 5.2.5 on 2025-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorversionrequirements',
            name='choose_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
