# Generated by Django 5.2.5 on 2025-08-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworksheetclass',
            name='worksheet_semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='worksheets.userworksheetsemester'),
            preserve_default=False,
        ),
    ]
