# Generated by Django 5.2.5 on 2025-08-26 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDistribution',
            fields=[
                ('code', models.CharField(choices=[('HU', 'Humanities & Arts'), ('SO', 'Social Sciences'), ('SC', 'Sciences'), ('QR', 'Quantitative Reasoning'), ('WR', 'Writing'), ('L1', 'Language Level 1'), ('L2', 'Language Level 2'), ('L3', 'Language Level 3'), ('L4', 'Language Level 4'), ('L5', 'Language Level 5')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('credits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('distributionals', models.ManyToManyField(blank=True, to='courses.coursedistribution')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_dept', models.CharField(max_length=10)),
                ('course_num', models.CharField(max_length=4)),
                ('course_year', models.PositiveIntegerField()),
                ('course_season', models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall')], max_length=10)),
                ('professor', models.CharField(max_length=50)),
                ('section_num', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('credits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('course_dept', models.CharField(max_length=10)),
                ('course_num', models.CharField(max_length=4)),
                ('course_year', models.PositiveIntegerField()),
                ('course_season', models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall')], max_length=10)),
                ('professor', models.CharField(max_length=50)),
                ('distributionals', models.ManyToManyField(blank=True, to='courses.coursedistribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
