# Generated by Django 5.2.5 on 2025-08-26 04:45

from django.db import migrations


CODES = [
    ("Hu", "Humanities & Arts"),
    ("So", "Social Sciences"),
    ("Sc", "Sciences"),
    ("QR", "Quantitative Reasoning"),
    ("WR", "Writing"),
    ("L1", "Language Level 1"),
    ("L2", "Language Level 2"),
    ("L3", "Language Level 3"),
    ("L4", "Language Level 4"),
    ("L5", "Language Level 5"),
]


def forwards(apps, schema_editor):
    CourseDistribution = apps.get_model("courses", "CourseDistribution")
    for code, _ in CODES:
        CourseDistribution.objects.get_or_create(code=code)


def backwards(apps, schema_editor):
    CourseDistribution = apps.get_model("courses", "CourseDistribution")
    CourseDistribution.objects.filter(code__in=[c for c, _ in CODES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
