# Generated by Django 5.2.5 on 2025-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_distribution_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinstance',
            old_name='course_dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='courseinstance',
            old_name='course_num',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='courseinstance',
            old_name='course_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='courseinstance',
            old_name='course_year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
