# Generated by Django 5.2.5 on 2025-08-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_course_dept_courseinstance_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcourse',
            old_name='course_dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='customcourse',
            old_name='course_num',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='customcourse',
            old_name='course_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='customcourse',
            old_name='course_year',
            new_name='year',
        ),
    ]
