# Generated by Django 5.2.5 on 2025-08-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_course_dept_customcourse_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='number',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='external_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedistribution',
            name='code',
            field=models.CharField(choices=[('Hu', 'Humanities & Arts'), ('So', 'Social Sciences'), ('Sc', 'Sciences'), ('QR', 'Quantitative Reasoning'), ('WR', 'Writing'), ('L1', 'Language Level 1'), ('L2', 'Language Level 2'), ('L3', 'Language Level 3'), ('L4', 'Language Level 4'), ('L5', 'Language Level 5')], max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='course_codes',
            field=models.ManyToManyField(to='courses.coursecode'),
        ),
    ]
