# Generated by Django 5.2.5 on 2025-08-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecode_remove_courseinstance_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='professor',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='course_professors',
            field=models.ManyToManyField(to='courses.courseprofessor'),
        ),
    ]
