# Generated by Django 5.2.5 on 2025-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseprofessor_remove_courseinstance_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='section_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courseprofessor',
            name='external_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
